/*
 * Kala scheduler
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kalaclient

// InlineResponse200 struct for InlineResponse200
type InlineResponse200 struct {
	Job Job `json:"job,omitempty"`
}
