/*
 * Kala scheduler
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kalaclient

// RemoteProperties struct for RemoteProperties
type RemoteProperties struct {
	Url                   string              `json:"url,omitempty"`
	Method                string              `json:"method,omitempty"`
	Body                  string              `json:"body,omitempty"`
	Headers               map[string][]string `json:"headers,omitempty"`
	Timeout               int64               `json:"timeout,omitempty"`
	ExpectedResponseCodes []int64             `json:"expected_response_codes,omitempty"`
}
