/*
 * Kala scheduler
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kalaclient

// JobWithId struct for JobWithId
type JobWithId struct {
	Id string `json:"id,omitempty"`
}
