/*
 * Kala scheduler
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kalaclient

// InlineResponse400 struct for InlineResponse400
type InlineResponse400 struct {
	Error string `json:"error,omitempty"`
}
